from sqlalchemy import Column, Integer, String, Float, DateTime, Date, Boolean, Text, JSON
from sqlalchemy.sql import func
from database import Base


class HeroSalesData(Base):
    """Historical sales transaction records."""
    __tablename__ = "hero_sales_data"

    id = Column(Integer, primary_key=True, index=True)
    invoice_date = Column(Date, nullable=False, index=True)
    sku_code = Column(String(50), nullable=False, index=True)
    model_name = Column(String(100), nullable=False, index=True)
    variant = Column(String(100), nullable=False)
    colour = Column(String(50), nullable=False)
    quantity_sold = Column(Integer, nullable=False, default=1)
    unit_price = Column(Float, nullable=False)
    total_value = Column(Float, nullable=False)
    location = Column(String(100), nullable=True)
    region = Column(String(50), nullable=True)
    source_type = Column(String(20), nullable=False, server_default="sample")  # sample | uploaded
    uploaded_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class ForecastData(Base):
    """Forecast predictions per SKU per day."""
    __tablename__ = "forecast_data"

    id = Column(Integer, primary_key=True, index=True)
    forecast_date = Column(Date, nullable=False, index=True)
    sku_code = Column(String(50), nullable=False, index=True)
    model_name = Column(String(100), nullable=False)
    variant = Column(String(100), nullable=False)
    colour = Column(String(50), nullable=False)
    predicted_quantity = Column(Float, nullable=False)
    confidence_lower = Column(Float, nullable=False)
    confidence_upper = Column(Float, nullable=False)
    festival_boost = Column(Float, default=1.0)
    forecast_method = Column(String(30), default="seasonal_trend")
    created_at = Column(DateTime, server_default=func.now())


class DispatchRecommendation(Base):
    """Dispatch planning recommendations per SKU."""
    __tablename__ = "dispatch_recommendations"

    id = Column(Integer, primary_key=True, index=True)
    recommendation_date = Column(Date, nullable=False, index=True)
    sku_code = Column(String(50), nullable=False, index=True)
    model_name = Column(String(100), nullable=False)
    variant = Column(String(100), nullable=False)
    colour = Column(String(50), nullable=False)
    recommended_quantity = Column(Integer, nullable=False)
    buffer_stock = Column(Integer, nullable=False)
    total_dispatch = Column(Integer, nullable=False)
    risk_score = Column(Float, nullable=False)  # 0–1
    risk_type = Column(String(20), default="neutral")  # overstock | understock | neutral
    working_capital_impact = Column(Float, nullable=False)
    festival_factor = Column(Float, default=1.0)
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, server_default=func.now())


class SKUPerformance(Base):
    """Aggregated performance metrics per SKU (refreshed periodically)."""
    __tablename__ = "sku_performance"

    id = Column(Integer, primary_key=True, index=True)
    sku_code = Column(String(50), nullable=False, unique=True, index=True)
    model_name = Column(String(100), nullable=False)
    variant = Column(String(100), nullable=False)
    colour = Column(String(50), nullable=False)
    total_units_sold = Column(Integer, default=0)
    total_revenue = Column(Float, default=0.0)
    yoy_growth_percent = Column(Float, nullable=True)
    mom_growth_percent = Column(Float, nullable=True)
    last_month_units = Column(Integer, default=0)
    current_month_units = Column(Integer, default=0)
    avg_monthly_units = Column(Float, default=0.0)
    seasonality_peak_month = Column(Integer, nullable=True)
    is_slow_moving = Column(Boolean, default=False)
    dead_stock_risk = Column(Float, default=0.0)  # 0–1
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())


class Alert(Base):
    """Smart alerts generated by the analytics engine."""
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    alert_type = Column(String(50), nullable=False, index=True)
    priority = Column(String(10), default="medium")  # high | medium | low
    title = Column(String(200), nullable=False)
    message = Column(Text, nullable=False)
    sku_code = Column(String(50), nullable=True)
    related_festival = Column(String(100), nullable=True)
    action_required = Column(Boolean, default=True)
    is_dismissed = Column(Boolean, default=False)
    expires_at = Column(Date, nullable=True)
    created_at = Column(DateTime, server_default=func.now())


class MarketIntelligence(Base):
    """External market data snapshots."""
    __tablename__ = "market_intelligence"

    id = Column(Integer, primary_key=True, index=True)
    data_date = Column(Date, nullable=False, index=True)
    source = Column(String(50), nullable=False)
    category = Column(String(50), nullable=False)  # trends | news | ev | fuel
    title = Column(String(300), nullable=False)
    summary = Column(Text, nullable=True)
    impact_score = Column(Float, nullable=True)  # -1 to 1
    raw_data = Column(JSON, nullable=True)
    created_at = Column(DateTime, server_default=func.now())
